export const INCREMENT_NUMBER = "INCREMENT_NUMBER";
export const DECREMENT_NUMBER = "DECREMENT_NUMBER";
export const INCREMENT_NUMBER_ICECREAM = "INCREMENT_NUMBER_ICECREAM";
export const DECREMENT_NUMBER_ICECREAM = "DECREMENT_NUMBER_ICECREAM";
export const BUDGET_ADD_EXPENSIS = "BUDGET_ADD_EXPENSIS";
export const BUDGET_REMOVE_EXPENSIS = "BUDGET_REMOVE_EXPENSTS";
export const BUDGET_EDIT_EXPENSIS = "BUDGET_EDIT_EXPENSIS";
export const BUDGET_NUMBER_ICECREAM = "BUDGET_NUMBER_ICECREAM";



